name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: pnpm i

      - name: lighthouse mobile audit
        run: pnpm lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_POST_DATABASE: ${{ secrets.NOTION_POST_DATABASE }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}
          WAKATIME_REFRESH_TOKEN: ${{ secrets.WAKATIME_REFRESH_TOKEN }}
          WAKATIME_CLIENT_ID: ${{ secrets.WAKATIME_CLIENT_ID }}
          WAKATIME_CLIENT_SECRET: ${{ secrets.WAKATIME_CLIENT_SECRET }}
          HUAMI_TOKEN: ${{ secrets.HUAMI_TOKEN }}

      - name: lighthouse desktop audit
        run: pnpm lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_POST_DATABASE: ${{ secrets.NOTION_POST_DATABASE }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}
          WAKATIME_REFRESH_TOKEN: ${{ secrets.WAKATIME_REFRESH_TOKEN }}
          WAKATIME_CLIENT_ID: ${{ secrets.WAKATIME_CLIENT_ID }}
          WAKATIME_CLIENT_SECRET: ${{ secrets.WAKATIME_CLIENT_SECRET }}
          HUAMI_TOKEN: ${{ secrets.HUAMI_TOKEN }}
